### PR TITLE
Fix sendfile

### PR DESCRIPTION
**Pull request by fishcakez**
- Use transport module instead of :file
- Prevent client errors from raising a badarg
- Return :ok from response body fun (as per :cowboy spec)

### CODE REVIEW

**Comment by HashNuke** [comment]
Thank you @fishcakez for fixing this ~!

I can vouch for this fix.

I have an audio tag on my page, that uses a wav file - https://github.com/HashNuke/mogo-chat/blob/b82899f6dbcd389e72007497409f9dd403bf95db/web/templates/index.html.eex#L2

And when I load the page, I get this error (I wasn't able to reproduce it consistently, maybe because of the browser cache):

```
=ERROR REPORT==== 21-Feb-2014::13:50:25 ===
Ranch listener 'Elixir.MogoChat.Dynamo.HTTP' had connection process started with cowboy_protocol:start_link/4 at <0.3511.0> exit with reason: {[{reason,{badmatch,{error,closed}}},{mfa,{'Elixir.Dynamo.Cowboy.Handler',init,3}},{stacktrace,[{'Elixir.Dynamo.Cowboy.Connection','-sendfile/3-fun-0-',3,[{file,"lib/dynamo/cowboy/connection.ex"},{line,158}]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,998}]},{'Elixir.Dynamo.Cowboy.Connection',sendfile,3,[{file,"lib/dynamo/cowboy/connection.ex"},{line,168}]},{'Elixir.Dynamo.Cowboy.Handler',init,3,[{file,"lib/dynamo/cowboy/handler.ex"},{line,14}]},{cowboy_handler,handler_init,4,[{file,"src/cowboy_handler.erl"},{line,69}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]},{req,[{socket,#Port<0.15448>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.3511.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{192,168,0,14},62525}},{host,<<"192.168.0.2">>},{host_info,undefined},{port,4000},{path,<<"/static/sounds/notify.wav">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"192.168.0.2:4000">>},{<<"range">>,<<"bytes=0-1">>},{<<"x-playback-session-id">>,<<"B7D9847E-051C-44F9-ACD1-F9F064384EEF">>},{<<"accept-encoding">>,<<"identity">>},{<<"accept">>,<<"*/*">>},{<<"accept-language">>,<<"en-gb">>},{<<"connection">>,<<"keep-alive">>},{<<"cookie">>,<<"_mogo_chat_session=8v+Z3vETE1gxq27FK41+sNic6LalYb29K0YKP3nyeFjqHD8HYFH+JoPbxqScZWgovvJHaNs9hs/+BW0rGMdgGsej7KGhIoAOCp46WPs6Y5OYE54DI+8Lbm1alfpBT2FW">>},{<<"user-agent">>,<<"AppleCoreMedia/1.0.0.11B554a (iPad; U; CPU OS 7_0_4 like Mac OS X; en_gb)">>}]},{p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{opts,'Elixir.MogoChat.Dynamo'}],[{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}

=ERROR REPORT==== 21-Feb-2014::13:50:25 ===
Error in process <0.3511.0> with exit value: {[{reason,{badmatch,{error,closed}}},{mfa,{'Elixir.Dynamo.Cowboy.Handler',init,3}},{stacktrace,[{'Elixir.Dynamo.Cowboy.Connection','-sendfile/3-fun-0-',3,[{file,"lib/dynamo/cowboy/connection.ex"},{line,158}]},{cowboy_req,reply...
```

@fishcakez helped on the Elixir IRC channel with this fix. However after using his fix, I've had no such errors.

**Comment by devinus** [comment]
Can we get a test that exercises this?

**Comment by HashNuke** [comment]
@devinus @fishcakez If you can tell me what/how it should test, I'll write a test for this.

**Comment by fishcakez** [comment]
@HashNuke I will write test this afternoon when have time :)

**Comment by fishcakez** [comment]
Added test for first bullet point (https sendfile support).

**Pull request merged**
