### PR TITLE
Added convenience function to delete data from a session given a key

### PR DESCRIPTION
**Pull request by sausheong**
Dynamo.HTTP.Session has the ability to put and to get data from the session, but not to delete. I've added a function to delete data from the session, also a simple test for session.

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @sausheong! Could you please rename the function to `delete_session`? That's how it would be named according to Elixir convention. :)

**Comment by sausheong** [comment]
Got it. I'll make the change.

Sau Sheong

On 12 Aug, 2013, at 4:49 PM, "José Valim" notifications@github.com wrote:

Thanks @sausheong https://github.com/sausheong! Could you please rename
the function to delete_session? That's how it would be named according to
Elixir convention. :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/elixir-lang/dynamo/pull/115#issuecomment-22480141
.

**Comment by aforward** [comment]
Hey José -- any chance of pulling this into elixir-lang/dynamo

**Comment by devinus** [comment]
:+1:

**Pull request merged**
