### PR TITLE
Fixed the issue #142

### PR DESCRIPTION
**Pull request by kamilc**
- Made the Dynamo.root function return correct value after
  moving the project to differently named directory

### CODE REVIEW

**Comment by josevalim** [comment]
Unfortunately we cannot depend on the position of `mix.exs` file because it may not be available once we do a release.

**Comment by kamilc** [comment]
The "bin" value in the root function in development mode points at something like this:
_someapp/tmp/dev/someapp_

The trivial solution would be return the path "../../../" (properly expanded of course).

Any other ideas? (more sane that is)?

**Comment by josevalim** [comment]
@kamilc yeah. :( that's because Dynamo does a hack in order to have different compile targets. We are going to change how compilation in Elixir works so Dynamo works better but I am not sure if there is any short term solution.  :( Thanks though for looking into this, it is good to have at least pin-pointed the root cause. :)

**Comment by kamilc** [comment]
@josevalim Ah - okay, that makes sense.

**Pull request closed without merging**
