### PR TITLE
Dynamo is using Exception.format_stacktrace_entry/2 which no longer exis...

### LINKED ISSUE #181: Dynamo is using Exception.format_stacktrace_entry/2 which no longer exists
Compiled lib/dynamo/base.ex
Compiled lib/dynamo/app.ex
Compiled lib/dynamo/connection/behaviour.ex
Compiled lib/dynamo/cowboy/handler.ex
Compiled lib/dynamo/connection/utils.ex
Compiled lib/dynamo/cowboy.ex
Compiled lib/dynamo.ex
== Compilation error on file lib/dynamo/filters/exceptions.ex ==
*\* (CompileError) lib/dynamo/filters/exceptions.ex:6: cannot import Exception.format_stacktrace_entry/2 because it doesn't exist
    (elixir) src/elixir_import.erl:58: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:20: :elixir_import.import/4
    (elixir) src/elixir_exp.erl:114: :elixir_exp.expand/2
    (stdlib-1.19.4) lists.erl:1339: :lists.mapfoldl/3
    (stdlib-1.19.4) lists.erl:1340: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:43: :elixir_exp.expand/2
    (elixir) src/elixir.erl:150: :elixir.quoted_to_erl/3

because of this the initial compilation of dynamo with MIX_ENV=test mix do deps.get, test fails.

### PR DESCRIPTION
**Pull request by fenfir**
Not sure if this belongs here or if format_stacktrace_entry/2 should be reinstated in Elixir, but it compiles and works for now.

fixes #181. Looking at the previous version of Exception in Elixir it
seemed as if the 2nd argument was optional.

### CODE REVIEW

**Comment by patrickdet** [comment]
oh nice. thanks

**Comment by devinus** [comment]
This makes it compile, but it's not "correct." I'm going to ping José to see what we're missing with the new exceptions.

**Comment by ericmj** [comment]
@devinus What is wrong with it? `format_stacktrace_entry` no longer needs to be given a path to get relative paths in stacktraces. All source file paths are relative now.

**Comment by devinus** [comment]
@ericmj Okay, that's all I wanted to ping José about, but the code should be a little refactored to not pass a second arg to `logger_stacktrace`.

**Comment by patrickdet** [comment]
so remove `conn.main.root` in line 42 and change logger_stacktrace/2 to logger_stacktrace/1 and that's it?

**Comment by devinus** [comment]
Fixed by bf865669ff76c975d1513733c945fc2179e8945e.

**Pull request closed without merging**
