### PR TITLE
An attempt at implementing basic support for websockets

### PR DESCRIPTION
**Pull request by mathieul**
The goal of this pull request is to give a shot at offering basic support for websockets, allowing to forward websocket requests to Cowboy websocket handlers.

It adds an `upgrade_to_websocket` function to connections to specify the handler module and the initial state to pass to `websocket_init`.

It also adds a `websocket` macro to the router DSL for a 1 line routing declaration.

Here is an example on how I use it [to interface with a pubsub server](https://gist.github.com/mathieul/6459540).

This is just a first draft to figure out if that's a direction you're interested in for the websocket support. Let me know what you think, thanks.

### CODE REVIEW

**Comment by josevalim** [comment]
Hello @mathieul!

Thank you so much for your work. The problem with this approach is that it is tied to Cowboy API. So I would rather provide a more generic way of passing options to cowboy, so one can turn websockets on and off rather than making it part of the Dynamo API. In fact, if you search the commit history, we had similar code in the past and it was removed exactly for this reason.

**Comment by mathieul** [comment]
@devinus it seems you didn't finish the sentence, what do you mean by Dynamo's APIs?

@josevalim I had 2 goals with this pull request: serve websocket requests with Dynamo so I can use its high level capabilities for HTTP rather than Cowboy, and learn more about writing Elixir. I achieved the 2nd one, I'm having a blast learning so much by hacking with Dynamo's code :smile:.

Do you think it would eventually make sense to write a higher level DSL to generate Cowboy websocket handlers with a simpler API (at least for the common tasks)?

I'll dig in more into Dynamo's connection workflow to figure out a good spot to insert a generic way to interface with Cowboy handlers like websockets and loops. Do you already have ideas about implementation?

**Comment by devinus** [comment]
What I tried to say: While I applaud the attempt, Dynamo's APIs would ideally abstract implementation details that your code doesn't yet.

**Comment by mathieul** [comment]
It makes sense, I completely agree with you. I actually just wanted to start the conversation. I have that need and I wanted to see if it was worth spending more time to make it usable to more before actually going all the way.

I'll look into finding a more generic entry point for interfacing with low level Cowboy handlers, and will play around with building a DSL for an easier and higher level API to implement websocket server behaviors.

Please let me know if you know of other previous attempts I could look at not to go through the same dead ends again, thanks.

**Pull request closed without merging**
