### PR TITLE
Can't compile cowboy, dependency not available

### PR DESCRIPTION
**Pull request by rafaellima**
[As described in this issue](https://github.com/elixir-lang/dynamo/issues/138) it fixes an error when compiling cowboy.

### CODE REVIEW

**Comment by edgurgel** [comment]
AFAIK, on current elixir, mix gets rebar dependencies and you should not need to define it.

**Comment by devinus** [comment]
@edgurgel That's true. @rafaellima Make sure you're on at least 0.10.2.

**Comment by rafaellima** [comment]
@edgurgel @devinus you were right, it was my elixir version. 

thanks,

**Comment by edgurgel** [comment]
:thumbsup:

**Pull request closed without merging**
