### PR TITLE
Some fixes for elixir v0.13.1

### PR DESCRIPTION
**Pull request by parroty**
Hi. I've tried to fix some errors while I was working on v0.13.1.

(1) Update elixir-lang/dynamo with dynamo/dynamo in Mix.Tasks.DynamoTest
  test update for https://github.com/dynamo/dynamo/commit/d14d2167c29474ee5b1e211ccc17ed891036c37d fix.

(2) Fix Mix.Project.compile_path for avoiding FunctionClauseError at v0.13.1
 It was causing [mix test] error. It seems because Path.join(nil, xxx) started raising exception at v0.13.1 after https://github.com/elixir-lang/elixir/commit/6624f31472bccc2c0ce456a94cc6532ae6c422f3, 

(3) Add tuple check logic for function_exported? as it is removed at elixir v0.13.1
  Tuple becomes unsupported for function_exported? (https://github.com/elixir-lang/elixir/commit/f9329379282515fab95efe7d5f2781c262303aac), and moved the logic into dynamo code.

### CODE REVIEW

**Comment by stevedomin** [comment]
@parroty my bad on d14d216 fix, didn't even run the tests for that one...

**Comment by chatman-media** [comment]
+1, doesn't work yet

**Comment by devinus** [comment]
@parroty Does this pass tests?

**Comment by parroty** [comment]
In my local environment, it passes.
(not sure how to run tests in travis for this commit. Also, .travis.yml may needs to be updated too)

**Pull request merged**
