### PR TITLE
Use elixir v0.13.1 for travis build

### PR DESCRIPTION
**Pull request by parroty**
How do you think about testing against the latest stable release? 
It seems some amount of changes are required for v0.13.2-dev regarding Maps.

### CODE REVIEW

**Comment by mgwidmann** [comment]
I just submitted [this pull request](https://github.com/dynamo/dynamo/pull/223).

**Comment by devinus** [comment]
The way this is usually handled is a version for 0.13.1 will be tagged and we will continue on Elixir master, but there has been a lot of changes on Elixir master right now and I have to review #223.

**Comment by parroty** [comment]
Thanks for the comment. I wasn't aware of the tagging policy.
It seems the latest one is v0.12.5. Can we get v0.13.1 one? I think current master works well on the v0.13.1.

**Comment by parroty** [comment]
Thanks for the tagging.

**Pull request closed without merging**
