### PR TITLE
Records -> Structs

### PR DESCRIPTION
**Pull request by mgwidmann**
Changed over all records (except one defrecordp, [connection](https://github.com/dynamo/dynamo/blob/master/lib/dynamo/connection/behaviour.ex#L66)) to structs (thanks @alco for helping!).

Using Binary.Dict to get rid of deprecation warning "Using records with the Dict module is deprecated, please use structs instead", maybe this should be extracted out of Dynamo?

Couldn't find what happened to `__ENV__.location`, replaced with `__ENV__.file` and `__ENV__.line` instead in tests.

The following lines still report deprecation warnings:
- test/dynamo_test.exs:40 DynamoTest."test defines root based on otp app"/1
- lib/dynamo/static.ex:45 Dynamo.Static.init/1
  Deprecation warning: "String.from_char_list!/1 is deprecated, please use String.from_char_data!/1 instead". 

These lines do not utilize Sting.from_char_list!/1, error line reporting incorrect?

### CODE REVIEW

**Comment by parroty** [comment]
Nice. I also tried to fix this one, but suspended at the Binary.Dict part :-)

> Couldn't find what happened to **ENV**.location, replaced with **ENV**.file and **ENV**.line instead in tests.

In the elixir itself, it's replaced as `Macro.Env.location(__ENV__)` in this commit (https://github.com/elixir-lang/elixir/commit/e5c13e6dd243aa35dcdf5c10141b3575d4541153) One option would be following this.

**Comment by parroty** [comment]
One tricky part might be this change throws the following error at v0.13.1 (as File.Stat is replaced with struct at v0.13.2-dev). Change dynamo-version or wait for v0.13.2? (which makes it difficult to pull from master?)

```
== Compilation error on file lib/dynamo/cowboy/connection.ex ==
** (CompileError) lib/dynamo/cowboy/connection.ex:155: File.Stat.__struct__/0 is undefined, cannot expand struct File.Stat
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_translator.erl:18: :elixir_translator.translate/2
    (elixir) src/elixir_translator.erl:350: :elixir_translator.translate_block/4
    (elixir) src/elixir_translator.erl:39: :elixir_translator.translate/2
    (elixir) src/elixir_clauses.erl:36: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:182: :elixir_def.translate_clause/7
```

**Comment by mgwidmann** [comment]
Ah yeah, didn't realize that was a 13.2 change. I can just change that piece back and do it as a separate pull request. Would be nice if master stayed functional...

**Comment by mgwidmann** [comment]
@parroty Also, would be nice if using a struct when the object is a record or vice versa was a little clearer. Should it be submitted as a bug?

**Comment by parroty** [comment]
Thanks for the reply. Regarding the version part, I might be overstepping (not confident how it should be).  Regarding struct, Elixir v0.13.0 guide states "Structs are meant to replace Elixir records", so this transition may be tentative one (if necessary, checking using is_record and is_map, or something?).

**Comment by mgwidmann** [comment]
Already made this PR 0.13.1 friendly ([in this commit](https://github.com/mgwidmann/dynamo/commit/8834d5b6755503d9cb61ae3a8461257d2a49a05b)), is it ready for acceptance?

**Comment by devinus** [comment]
@mgwidmann Can you rebase with master?

**Comment by mgwidmann** [comment]
All ready.

**Comment by devinus** [comment]
@mgwidmann This doesn't seem rebased with master yet. Can you make sure it's rebased and then squash it all into one commit?

**Comment by mgwidmann** [comment]
Closing this since its merged in a different pull request. Thanks!

**Pull request closed without merging**
