### PR TITLE
Add documentation for route globbing

### PR DESCRIPTION
**Pull request by ericmj**
There is no documentation that states that routes can match on globs. Should be added to the documentation of `Dynamo.Router.Base` and maybe the README walk-through of routers?

Example:

``` elixir
match "/hello/*glob" do
  conn.resp 200, "world"
end
```

### CODE REVIEW

**Comment by antongudkov** [comment]
@ericmj you just can use \* instead of *glob.  I think this feature is useful for handling 404 error, but if we forward some scope to another router, we can't handle this in application router. So it will be need to implement this logic to each router to handle 404 properly, which is not very сosily.

``` ruby
@prepare :render_without_layout
match "/*" do
  render conn.status(404), "errors/404"
end

defp render_without_layout(conn) do
  conn.assign :layout, nil
end
```

P.S. English is not my first language too :)

**Comment by ericmj** [comment]
@antongudkov thanks, didn't know that, will add \* to the documentation.

Could something like this solver your 404 handling?

``` elixir
defmodule RouterHelpers do
  defmacro handle_404 do
    quote do
      match "/*" do
        render conn.status(404), "errors/404"
      end
    end
  end
end
```

**Pull request merged**
