### PR TITLE
[WIP] Upgrade to Elixir 0.14.x

### PR DESCRIPTION
**Pull request by stevedomin**
This is a WIP of making Dynamo work with Elixir 0.14.x

There are still 9 specs failing, I'm publishing it because I'm kinda stuck so if anyone is willing to help that would be awesome.

I'm not 100% happy with the way I integrated maps but my goal was to get the specs passing and then gather feedback and see how we can improve that.

### CODE REVIEW

**Comment by stevedomin** [comment]
Here's the output of the failing specs: https://gist.github.com/stevedomin/b1406488e8f719412baa

Maybe someone with more Elixir experience will have idea on what's wrong just by looking at it.

**Comment by devinus** [comment]
@stevedomin :maps.merge requires both arguments to be a map.

**Comment by stevedomin** [comment]
Yes, I actually knew about that one, there's a lot of stuff that needs to be moved to maps

**Comment by nhu313** [comment]
I fixed all except one failing test. I don't know how to the pull request work, but I based it off your branch and send a pull request there. 

I couldn't figure out the failure in task_test because Mix.Utils.read_manifest was removed, but I don't know what we can use in place of it. Any idea?

Thanks for doing this :+1:  I really want to get dynamo up to date and start building my app :)

**Comment by xinuc** [comment]
can we update this to support 15.1 ?

**Pull request closed without merging**
