### PR TITLE
Instructions for running on Heroku

### PR DESCRIPTION
**Pull request by catsby**
Add a section to `README.md` with instructions for setting up a Dynamo project on Heroku.

### CODE REVIEW

**Comment by catsby** [comment]
Preview here: https://github.com/catsby/dynamo/blob/heroku_instructions/README.md#running-on-heroku

**Comment by josevalim** [comment]
Thanks @catsby, this is great! Instead of adding it to the README, could you please make it a guide? :)

**Comment by catsby** [comment]
Done: https://github.com/catsby/dynamo/blob/heroku_instructions/guides/how-to-heroku.md

Wasn't sure how/where to mention it in the `README`, should it be?

**Comment by josevalim** [comment]
I added it to the end of the README myself, thank you!

**Pull request merged**
