### PR TITLE
Can not fetch req_body

### PR DESCRIPTION
**Pull request by chatgris**
Hi,

I have some issue fetching the body of a request.

I tried to come up with a fix, but I got lost between fetch, aspect, body, req_body and raw_req_body. :cry:

So, I could not come up with anything better than a failing test. I would be glad to help fixing up this issue, but I would need some guidance. :nail_care:

Hope this helps!

### CODE REVIEW

**Comment by devinus** [comment]
And this is _failing_ test case?

**Comment by chatgris** [comment]
It does fail on my setup:

``` shell
 1) test prepare filter on body (Dynamo.Router.FiltersTest)
     ** (ExUnit.ExpectationError)
                  expected: nil
       to be equal to (==): "hello"
     at test/dynamo/router/filters_test.exs:39
```

``` shell
Erlang R16B (erts-5.10.1) [source-05f1189] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (0.11.2) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by devinus** [comment]
Okay, I'll merge this into a branch and look into it.

**Comment by chatgris** [comment]
With a request like:

``` shell
curl -XPOST "http://localhost:8888/filter?token=pr" -d "test"
```

Params looks like:

``` elixir
Binary.Dict<[{"token", "pr"}, {"test", nil}, {"glob", []}]>
```

But, by setting the Content-Type, I've got a body:

``` shell
curl -XPOST -H "Content-Type: application/json" "http://localhost:8888/filter?token=pr" -d "test"
```

I guess, this is link to: https://github.com/dynamo/dynamo/blob/master/lib/dynamo/cowboy/body_parser.ex#L11

**Comment by chatgris** [comment]
Fixed by #174

**Pull request closed without merging**
